### ISSUE TITLE
Saving option of entropy_db

### ISSUE THREAD

**Issue by sherryue123** [entropy-lab/entropy-qpu#10]
Hi Lior @liorella-qm, 

The issue comes from my previous questions:
It seems config is saved multiple times to entropy_db everytime I run a test graph (just one root and another toy QuaCalNode). Unfortunately, I have a large config, so entropy_db will grow ~9 MB each time. For more nodes in the graph, it should grow much faster, which is not sustainable. Is there any way around it?

And your answer
seems like we need an option to make a distinction between results of nodes (which always need to be saved to the entropy DB) and “ephemeral” outputs that don’t. Could you please open a ticket about this on entropy GitHub and assign  me? This will allow us to track it.

Please keep me posted about the update. I'd like to try new versions if there's progress.

Thanks,
Sherry

**Comment by liorella-qm** [comment]
Hi Sherry, indeed we'll add an option to not save the node output to prevent this issue. We'll keep you updated :-)

**Comment by sherryue123** [comment]
> Hi Sherry, indeed we'll add an option to not save the node output to prevent this issue. We'll keep you updated :-)

That will be helpful. Thank you!

**Comment by qguyk** [comment]
option to not save the node output was added to entropy: https://github.com/entropy-lab/entropy/pull/22
closing this issue
